# Generated by Django 3.2.7 on 2021-11-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_offer',
            field=models.IntegerField(null=True),
        ),
    ]
