# Generated by Django 3.2.7 on 2021-11-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
